### ISSUE TITLE
"JoinPath" not declared by package "net/url"

### ISSUE THREAD

**Issue by mimani68** [GoFarsi/paygap#6]
The golang problem appear seemingly based on lack of method "JoinPath" in "net/url"

line 90 -> `url, err := url.JoinPath(apiConfig.Host, apiConfig.Path)`

The persice output error shown below

```bash
# github.com/GoFarsi/paygap/client
client/client.go:96:18: undefined: url.JoinPath
```

**Comment by Ja7ad** [comment]
> The golang problem appear seemingly based on lack of method "JoinPath" in "net/url"
> 
> line 90 -> `url, err := url.JoinPath(apiConfig.Host, apiConfig.Path)`
> 
> The persice output error shown below
> 
> ```bash
> # github.com/GoFarsi/paygap/client
> client/client.go:96:18: undefined: url.JoinPath
> ```
> 

[url.JoinPath](https://pkg.go.dev/net/url#URL.JoinPath) added in version 1.19, Your compiler is ^1.19?
